

server:
  port: 9000


logging:
  config: classpath:logback/logback-srping.xml
  level:
    root: info




spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
    listener:
      concurrency: 1
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: -1

  datasource:
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: localpw
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.jdbc.batch_size: 300
      hibernate.order_inserts: true
      hibernate.order_updates: true
#      hibernate.generate_statistics: true

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
      connect-timeout: 60000

  rabbitmq:
    host: localhost
    port: 5672
    username: ruser
    password: localpw
    vhost: legacy